### ISSUE TITLE
Not work with Vaadin 7.7.3

### ISSUE THREAD

**Issue by ambrits** [fdreyfs/vaadin-tuning-datefield#15]
Hi!

I would like to use your add-on with the new Vaadin 7.7.x, but I have got an error message. Can ypu help me, how can I solve this problem?

java.lang.NoClassDefFoundError: com/google/gwt/thirdparty/guava/common/base/Objects
	at org.vaadin.addons.tuningdatefield.TuningDateField.setLocale(TuningDateField.java:448)

**Comment by fdreyfs** [comment]
Hi,
Can you try version 0.17.0 I just published ?
Cheers
Fred

**Comment by ambrits** [comment]
Great! Thank you for your very quickly help!

**Comment by fdreyfs** [comment]
Good to hear it's working.
Please rate the plugin if you haven't done it yet.
Cheers
Fred

**Comment by fdreyfs** [comment]
Your welcome,
Do not hesitate to rate the plugin if you haven't done it yet.
Regards,

Fred
